=== liuxfiu/primogeni/netscript/bin/jprime/primex.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="model">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="node" type="nodeType" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="nodeType">
		<xs:sequence>
			<xs:element name="attribute" type="singleAttributeType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="attributeList" type="listAttributeType" minOccurs="0" maxOccurs="unbounded" />
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="node" type="nodeType" />
				<xs:element name="ref" type="nodeRefType" />
				<xs:element name="replica" type="nodeReplicaType" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="type" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="nodeRefType">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="path" type="xs:string" use="required" />
	</xs:complexType>
	
	<xs:complexType name="nodeReplicaType">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="path" type="xs:string" use="required" />
	</xs:complexType>
		
	<xs:complexType name="listAttributeType">
		<xs:sequence>
			<xs:element name="attribute" type="singleAttributeType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>
	
	<xs:complexType name="singleAttributeType">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="required" />
	</xs:complexType>

</xs:schema>

=== liuxfiu/primogeni/netsim/regression-tests/test-tcp-behavior-scalable.xml
<?xml version="1.0" ?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="primex.xsd">
	<node name="topnet" type="Net" >
		<!-- RoutingSphere name=RoutingSphere_4 numRoutes=6  -->
		<node name="router1" type="Router" >
			<node name="ifr11" type="Interface" >
			</node>
			<node name="ifr12" type="Interface" >
				<attribute name="buffer_size" value="64000" />
			</node>
		</node>
		<node name="router2" type="Router" >
			<node name="ifr21" type="Interface" >
				<attribute name="buffer_size" value="64000" />
			</node>
			<node name="ifr22" type="Interface" >
			</node>
		</node>
		<node name="host1" type="Router" >
			<node name="if0" type="Interface" >
			</node>
			<node name="TCPMaster_17" type="TCPMaster" >
				<attribute name="mss" value="1448" />
				<attribute name="samplingInterval" value="0.1" />
				<attribute name="tcpCA" value="scalable" />
			</node>
		</node>
		<node name="host2" type="Router" >
			<node name="if0" type="Interface" >
			</node>
			<node name="TCPMaster_23" type="TCPMaster" >
				<attribute name="mss" value="1448" />
				<attribute name="samplingInterval" value="0.1" />
				<attribute name="tcpCA" value="scalable" />
			</node>
			<node name="HTTPServer_27" type="HTTPServer" >
			</node>
		</node>
		<node name="h1_router" type="Link" >
			<attribute name="bandwidth" value="1000000000" />
			<attribute name="delay" value="0.0" />
			<ref name="InterfaceAlias_31" path="..:host1:if0" />
			<ref name="InterfaceAlias_33" path="..:router1:ifr11" />
		</node>
		<node name="router_router" type="Link" >
			<attribute name="bandwidth" value="10000000" />
			<attribute name="delay" value="0.064" />
			<ref name="InterfaceAlias_38" path="..:router1:ifr12" />
			<ref name="InterfaceAlias_40" path="..:router2:ifr21" />
		</node>
		<node name="router_h2" type="Link" >
			<attribute name="bandwidth" value="1000000000" />
			<attribute name="delay" value="0.0" />
			<ref name="InterfaceAlias_45" path="..:router2:ifr22" />
			<ref name="InterfaceAlias_47" path="..:host2:if0" />
		</node>
		<node name="Traffic_49" type="Traffic" >
			<node name="TCPTraffic_50" type="TCPTraffic" >
				<attribute name="connections_per_session" value="1" />
				<attribute name="dst_port" value="80" />
				<attribute name="dsts" value=".:host2" />
				<attribute name="file_size" value="70000000" />
				<attribute name="session_timeout" value="3000" />
				<attribute name="srcs" value=".:host1" />
			</node>
		</node>
		<node name="3" type="ShortestPath" />
	</node>
</model>

=== liuxfiu/primogeni/netscript/foobarmodel2.xml
<?xml version="1.0" ?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="primex.xsd">
	<node name="top" type="Net" >
		<attribute name="sub_edge_ifaces" value="[[108, 129], [268, 289]]" symbol="false" />
		<!-- RoutingSphere name=_rsphere_ numRoutes=2  -->
		<node name="_viz_agg_" type="VizAggregate" >
			<attribute name="var_id" value="161" symbol="false" />
		</node>
		<node name="left" type="Net" >
			<!-- RoutingSphere name=_rsphere_ numRoutes=12  -->
			<node name="_viz_agg_" type="VizAggregate" >
				<attribute name="var_id" value="161" symbol="false" />
			</node>
			<node name="h1" type="Host" >
				<node name="if0" type="Interface" >
				</node>
			</node>
			<node name="h2" type="Host" >
				<node name="if0" type="Interface" >
				</node>
			</node>
			<node name="h3" type="Host" >
				<node name="if0" type="Interface" >
				</node>
			</node>
			<node name="h4" type="Host" >
				<node name="if0" type="Interface" >
				</node>
			</node>
			<node name="r" type="Router" >
				<node name="if1" type="Interface" >
				</node>
				<node name="if2" type="Interface" >
				</node>
				<node name="if3" type="Interface" >
				</node>
				<node name="if4" type="Interface" >
				</node>
				<node name="if0" type="Interface" >
				</node>
			</node>
			<node name="Link_22" type="Link" >
				<ref name="InterfaceAlias_23" path="..:h1:if0" />
				<ref name="InterfaceAlias_25" path="..:r:if1" />
			</node>
			<node name="Link_26" type="Link" >
				<ref name="InterfaceAlias_27" path="..:h2:if0" />
				<ref name="InterfaceAlias_29" path="..:r:if2" />
			</node>
			<node name="Link_30" type="Link" >
				<ref name="InterfaceAlias_31" path="..:h3:if0" />
				<ref name="InterfaceAlias_33" path="..:r:if3" />
			</node>
			<node name="Link_34" type="Link" >
				<ref name="InterfaceAlias_35" path="..:h4:if0" />
				<ref name="InterfaceAlias_37" path="..:r:if4" />
			</node>
			<node name="__dynamic_traffics__" type="Traffic" >
			</node>
			<node name="8" type="ShortestPath" />
		</node>
		<node name="right_net" type="Net" >
			<!-- RoutingSphere name=_rsphere_ numRoutes=12  -->
			<node name="_viz_agg_" type="VizAggregate" >
				<attribute name="var_id" value="161" symbol="false" />
			</node>
			<node name="h1" type="Host" >
				<node name="if0" type="Interface" >
				</node>
			</node>
			<node name="h2" type="Host" >
				<node name="if0" type="Interface" >
				</node>
			</node>
			<node name="h3" type="Host" >
				<node name="if0" type="Interface" >
				</node>
			</node>
			<node name="h4" type="Host" >
				<node name="if0" type="Interface" >
				</node>
			</node>
			<node name="r" type="Router" >
				<node name="if1" type="Interface" >
				</node>
				<node name="if2" type="Interface" >
				</node>
				<node name="if3" type="Interface" >
				</node>
				<node name="if4" type="Interface" >
				</node>
				<node name="if0" type="Interface" >
				</node>
			</node>
			<node name="Link_22" type="Link" >
				<ref name="InterfaceAlias_23" path="..:h1:if0" />
				<ref name="InterfaceAlias_25" path="..:r:if1" />
			</node>
			<node name="Link_26" type="Link" >
				<ref name="InterfaceAlias_27" path="..:h2:if0" />
				<ref name="InterfaceAlias_29" path="..:r:if2" />
			</node>
			<node name="Link_30" type="Link" >
				<ref name="InterfaceAlias_31" path="..:h3:if0" />
				<ref name="InterfaceAlias_33" path="..:r:if3" />
			</node>
			<node name="Link_34" type="Link" >
				<ref name="InterfaceAlias_35" path="..:h4:if0" />
				<ref name="InterfaceAlias_37" path="..:r:if4" />
			</node>
			<node name="__dynamic_traffics__" type="Traffic" >
			</node>
			<node name="38" type="ShortestPath" />
		</node>
		<node name="toplink" type="Link" >
			<ref name="InterfaceAlias_70" path="..:left:r:if0" />
			<ref name="InterfaceAlias_72" path="..:right_net:r:if0" />
		</node>
		<node name="Traffic_73" type="Traffic" >
			<node name="TCPTraffic_74" type="TCPTraffic" >
				<attribute name="dsts" value="01021
001064
Host01023
189" symbol="false" />
				<attribute name="mapping" value="one2one" symbol="false" />
				<attribute name="srcs" value="01021
001064
Host01022
29" symbol="false" />
				<attribute name="start_time" value="10.0" symbol="false" />
				<attribute name="file_size" value="1000000000" symbol="false" />
				<attribute name="number_of_sessions" value="1" symbol="false" />
				<attribute name="interval" value="1.0" symbol="false" />
				<attribute name="interval_exponential" value="false" symbol="false" />
			</node>
			<node name="TCPTraffic_75" type="TCPTraffic" >
				<attribute name="dsts" value="01021
001064
Host01023
189" symbol="false" />
				<attribute name="mapping" value="one2one" symbol="false" />
				<attribute name="srcs" value="01021
001064
Host01022
52" symbol="false" />
				<attribute name="start_time" value="13.0" symbol="false" />
				<attribute name="file_size" value="10000000000" symbol="false" />
				<attribute name="number_of_sessions" value="2" symbol="false" />
				<attribute name="interval" value="1.0" symbol="false" />
				<attribute name="interval_exponential" value="false" symbol="false" />
			</node>
		</node>
		<node name="__dynamic_traffics__" type="Traffic" >
		</node>
		<node name="3" type="ShortestPath" />
	</node>
</model>

=== liuxfiu/primogeni/netscript/tcptester.xml
<?xml version="1.0" ?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="primex.xsd">
	<node name="topnet" type="Net" >
		<!-- RoutingSphere name=_rsphere_ numRoutes=42  -->
		<node name="_viz_agg_" type="VizAggregate" >
			<attribute name="var_id" value="161" symbol="false" />
		</node>
		<node name="router1" type="Router" >
			<node name="r_2" type="Interface" >
			</node>
			<node name="ifh0" type="Interface" >
				<attribute name="bit_rate" value="1000000000000" symbol="false" />
				<attribute name="buffer_size" value="64000" symbol="false" />
				<attribute name="latency" value="0.0" symbol="false" />
			</node>
			<node name="ifh1" type="Interface" >
				<attribute name="bit_rate" value="1000000000000" symbol="false" />
				<attribute name="buffer_size" value="64000" symbol="false" />
				<attribute name="latency" value="0.0" symbol="false" />
			</node>
			<node name="ifh2" type="Interface" >
				<attribute name="bit_rate" value="1000000000000" symbol="false" />
				<attribute name="buffer_size" value="64000" symbol="false" />
				<attribute name="latency" value="0.0" symbol="false" />
			</node>
		</node>
		<node name="router2" type="Router" >
			<node name="r_1" type="Interface" >
			</node>
			<node name="ifh0" type="Interface" >
				<attribute name="bit_rate" value="1000000000000" symbol="false" />
				<attribute name="buffer_size" value="64000" symbol="false" />
				<attribute name="latency" value="0.0" symbol="false" />
			</node>
			<node name="ifh1" type="Interface" >
				<attribute name="bit_rate" value="1000000000000" symbol="false" />
				<attribute name="buffer_size" value="64000" symbol="false" />
				<attribute name="latency" value="0.0" symbol="false" />
			</node>
			<node name="ifh2" type="Interface" >
				<attribute name="bit_rate" value="1000000000000" symbol="false" />
				<attribute name="buffer_size" value="64000" symbol="false" />
				<attribute name="latency" value="0.0" symbol="false" />
			</node>
		</node>
		<node name="toplink" type="Link" >
			<attribute name="bandwidth" value="1000000000000" symbol="false" />
			<attribute name="delay" value="0.01" symbol="false" />
			<ref name="InterfaceAlias_13" path="..:router1:r_2" />
			<ref name="InterfaceAlias_16" path="..:router2:r_1" />
		</node>
		<node name="l0" type="Host" >
			<node name="if0" type="Interface" >
				<attribute name="bit_rate" value="1000000000000" symbol="false" />
				<attribute name="buffer_size" value="64000" symbol="false" />
				<attribute name="latency" value="0.0" symbol="false" />
				<node name="OpenVPNEmulation_30" type="OpenVPNEmulation" >
				</node>
			</node>
		</node>
		<node name="r0" type="Host" >
			<node name="if0" type="Interface" >
				<attribute name="bit_rate" value="1000000000000" symbol="false" />
				<attribute name="buffer_size" value="64000" symbol="false" />
				<attribute name="latency" value="0.0" symbol="false" />
				<node name="OpenVPNEmulation_36" type="OpenVPNEmulation" >
				</node>
			</node>
		</node>
		<node name="ll0" type="Link" >
			<attribute name="bandwidth" value="1000000000000" symbol="false" />
			<attribute name="delay" value="0.01" symbol="false" />
			<ref name="InterfaceAlias_41" path="..:l0:if0" />
			<ref name="InterfaceAlias_43" path="..:router1:ifh0" />
		</node>
		<node name="rl0" type="Link" >
			<attribute name="bandwidth" value="1000000000000" symbol="false" />
			<attribute name="delay" value="0.01" symbol="false" />
			<ref name="InterfaceAlias_48" path="..:r0:if0" />
			<ref name="InterfaceAlias_50" path="..:router2:ifh0" />
		</node>
		<node name="l1" type="Host" >
			<node name="if0" type="Interface" >
				<attribute name="bit_rate" value="1000000000000" symbol="false" />
				<attribute name="buffer_size" value="64000" symbol="false" />
				<attribute name="latency" value="0.0" symbol="false" />
			</node>
		</node>
		<node name="r1" type="Host" >
			<node name="if0" type="Interface" >
				<attribute name="bit_rate" value="1000000000000" symbol="false" />
				<attribute name="buffer_size" value="64000" symbol="false" />
				<attribute name="latency" value="0.0" symbol="false" />
			</node>
		</node>
		<node name="ll1" type="Link" >
			<attribute name="bandwidth" value="1000000000000" symbol="false" />
			<attribute name="delay" value="0.01" symbol="false" />
			<ref name="InterfaceAlias_73" path="..:l1:if0" />
			<ref name="InterfaceAlias_75" path="..:router1:ifh1" />
		</node>
		<node name="rl1" type="Link" >
			<attribute name="bandwidth" value="1000000000000" symbol="false" />
			<attribute name="delay" value="0.01" symbol="false" />
			<ref name="InterfaceAlias_80" path="..:r1:if0" />
			<ref name="InterfaceAlias_82" path="..:router2:ifh1" />
		</node>
		<node name="l2" type="Host" >
			<node name="if0" type="Interface" >
				<attribute name="bit_rate" value="1000000000000" symbol="false" />
				<attribute name="buffer_size" value="64000" symbol="false" />
				<attribute name="latency" value="0.0" symbol="false" />
			</node>
		</node>
		<node name="r2" type="Host" >
			<node name="if0" type="Interface" >
				<attribute name="bit_rate" value="1000000000000" symbol="false" />
				<attribute name="buffer_size" value="64000" symbol="false" />
				<attribute name="latency" value="0.0" symbol="false" />
			</node>
		</node>
		<node name="ll2" type="Link" >
			<attribute name="bandwidth" value="1000000000000" symbol="false" />
			<attribute name="delay" value="0.01" symbol="false" />
			<ref name="InterfaceAlias_105" path="..:l2:if0" />
			<ref name="InterfaceAlias_107" path="..:router1:ifh2" />
		</node>
		<node name="rl2" type="Link" >
			<attribute name="bandwidth" value="1000000000000" symbol="false" />
			<attribute name="delay" value="0.01" symbol="false" />
			<ref name="InterfaceAlias_112" path="..:r2:if0" />
			<ref name="InterfaceAlias_114" path="..:router2:ifh2" />
		</node>
		<node name="__dynamic_traffics__" type="Traffic" >
		</node>
		<node name="3" type="ShortestPath" />
	</node>
</model>
